### ISSUE TITLE
Categories page has issues

### ISSUE THREAD

**Issue by jamescooke** [jamescooke/droidstrap#9]
Looks like Categories page is generated but not linked or styled.

E.g from my site : http://jamescooke.info/categories.html

**Comment by sahensley** [comment]
James - thanks for the great theme.

It looks like this issue is due to a missing categories.html template.  Since the theme doesn't have a categories template, it is falling back to the Simple theme (included with Pelican).

Here's the Simple template it is falling back to:
```jinja2
{% extends "base.html" %}
{% block content %}
<ul>
{% for category, articles in categories %}
    <li><a href="{{ SITEURL }}/{{ category.url }}">{{ category }}</a></li>
{% endfor %}
</ul>
{% endblock %}
```

I've added a newer version of the categories.html template from the Simple theme to my fork and the output is a bit nicer with a heading and category counts.

```jinja2
{% extends "base.html" %}

{% block title %}{{ SITENAME }} - Categories{% endblock %}

{% block content %}
    <h1>Categories on {{ SITENAME }}</h1>
    <ul>
    {% for category, articles in categories|sort %}
        <li><a href="{{ SITEURL }}/{{ category.url }}">{{ category }}</a> ({{ articles|count }})</li>
    {% endfor %}
    </ul>
{% endblock %}
```

To link the page, I've added this to my pelicanconf.py file:
```python
CATEGORIES_SAVE_AS = 'categories/index.html'
MENUITEMS = [
        ('Categories', '/categories/'),
]
```

The individual categories are also automatically linked in the sidebar if `DISPLAY_CATEGORIES_ON_MENU = True` is set.

Would you like a PR with the file added?

**Comment by jamescooke** [comment]
Hi @sahensley - Yes please a PR would be great :+1:
